apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: nginx-giropops
  name: nginx_giropops
spec:
  containers:
  - image: nginx
    name: nginx_giropops
    ports:
    - containerPort: 80
    resources: 
      limits: 
        memory: "128Mi"
        cpu: "0.5"
    requests:
        memory: "128Mi"
        cpu: "0.3"
  dnsPolicy: ClusterSecond
  restartPolicy: Always