FROM cgr.dev/chainguard/python:latest-dev
WORKDIR /app
COPY requirements.txt .
# Instalação sem --user
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
COPY templates templates/
COPY static static/
EXPOSE 5000
# Usando python -m flask
ENTRYPOINT ["python", "-m", "flask", "run", "--host=0.0.0.0"]
